name: deploy
run-name: deploy
concurrency:
  group: ci-${{ github.repositoryUrl }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
jobs:
  releaseApp:
    runs-on: arc-runner-set
    permissions:
      contents: read
      packages: write
    env:
      DINGTALK_ACCESS_TOKEN: ${{ secrets.DINGTALK_ACCESS_TOKEN }}
      DINGTALK_SECRET: ${{ secrets.DINGTALK_SECRET }}
      REGISTRY_PKG_PATH: /buff/lol-api
      HELM_PKG: oci://k-harbor.buffge.com/library/buff-app
      HELM_RELEASE_MAME: lol-api
      K8S_NS: buff
    steps:
      - name: Check out repository code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Build Docker image
        run: |
          BUILD_TIME=`TZ="Asia/Shanghai" date '+%Y-%m-%d_%H:%M:%S-%Z'`
          echo "BUILD_TIME=$BUILD_TIME" >> $GITHUB_ENV
          sudo nerdctl -n k8s.io build \
            --build-arg buildUser='${{github.actor}}' \ 
            --build-arg buildTime='${{env.BUILD_TIME}}' \ 
            --build-arg commitID='${{github.sha}}' \ 
            --build-arg commitMsg='${{ github.event.head_commit.message }}' \ 
            -t ${{ secrets.REGISTRY}}${{env.REGISTRY_PKG_PATH}}:${{ github.sha }} .
        shell: bash
      - name: Docker login
        run: sudo nerdctl login -u ${{ secrets.HARBOR_NAME }} -p ${{ secrets.HARBOR_PWD }} ${{ secrets.REGISTRY}}
      - name: Push Docker image
        run: |
          sudo nerdctl -n k8s.io push ${{ secrets.REGISTRY}}${{env.REGISTRY_PKG_PATH}}:${{ github.sha }}
      - name: helm upgrade
        run: |
          helm upgrade -i ${{env.HELM_RELEASE_MAME}}  ${{env.HELM_PKG}}  --atomic --timeout 30s \
          --set image.tag=${{ github.sha }} -f ./docker/values.yml -n ${{env.K8S_NS}}
      - uses: buffge/dingtalk-action@34743c736212579f8ff99d2dca75879b56371796
        if: ${{ success() }}
        with:
          msgtype: markdown
          title: " lol-api 成功"
          text: |
            **<font color=#54aeff size=4>az-lol 构建成功</font>**
            
            **<font size=4>commitMsg: ${{ github.event.head_commit.message }}</font>**
      - uses: buffge/dingtalk-action@34743c736212579f8ff99d2dca75879b56371796
        if: ${{ failure() }}
        with:
          msgtype: markdown
          title: "lol-api 失败"
          text: |
            **<font color=#cf222e size=4>az-lol 构建失败</font>**

            **<font size=4>commitMsg: ${{ github.event.head_commit.message }}</font>**
